# Name of the workflow
name: hello-world
# Event to trigger the workflow on
on: push
# What happens when the event triggers
jobs:
  hellow-world-job:
    # Specify runner: where to execute this job
    # ubuntu-latest: GitHub hosted runner
    runs-on: ubuntu-latest
    # steps: Optional, but best practice
    steps:
      # First actions
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hellow_world.text)"
